language: csharp

mono:
  - latest

sudo: required

services:
  - docker

before_install:
  - echo "###--- Install step."
  - ./build.sh

script:
  - echo "###--- Test step."
  - ./test.sh

branches:
  only:
    - master
    - dev
    - libgdx
