language: android

jdk:
  - oraclejdk8

android:
  components:
     - tools
     - build-tools-26.0.1
     - tools
     - platform-tools
     - android-26
     - extra-google-m2repository
     - extra-android-m2repository

install:
  - echo "### Install step"
  - echo $ANDROID_HOME
  - echo ~/.android
  - chmod +rw ~/.android
  - chmod +x gradlew

script:
  - echo "### Test step"
  - ./gradlew assemble
  - ./gradlew test

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
