language: android

jdk:
  - oraclejdk8

android:
  components:
     - tools
     - build-tools-26.0.1
     - tools
     - platform-tools
     - android-26
     - extra-google-m2repository
     - extra-android-m2repository
#  licenses:
#    - 'android-sdk-.+'
#    - 'google-gdk-.+'

before_install:
  - echo "###--- Before install step"
  - chmod +x gradlew

install:
  - echo "###--- Install step"
#  - echo y | android update sdk -u -a -t build-tools-26.0.1
#  - echo y | android update sdk -u -a -t tools
#  - echo y | android update sdk -u -a -t platform-tools
#  - echo y | android update sdk -u -a -t android-26
#  - echo y | android update sdk -u -a -t extra-google-m2repository
#  - echo y | android update sdk -u -a -t extra-android-m2repository

script:
  - echo "###--- Test step"
  - ./gradlew assemble
  - ./gradlew test

branches:
  only:
    - master
    - dev
    - libgdx

matrix:
  fast_finish: true
