language: android

jdk:
  - oraclejdk8

android:
  components:
     - tools
     - build-tools-27.0.1
     - tools
     - platform-tools
     - android-27

install:
  - echo "### Install step"
  - cp debug.keystore ~/.android
  - chmod +x gradlew

script:
  - echo "### Test step"
  - ./gradlew assemble
  - ./gradlew test

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
